### ISSUE TITLE
ability to restart the rest API automatically

### ISSUE THREAD

**Issue by Rafi993** [firstopinion/endpoints#51]
How do I restart rest API automatically in case it fails. Is there some thing like nodejs's pm2 or forever for endpoint in python.

**Comment by Jaymon** [comment]
I'm not sure I fully understand what specifically you are asking for, internally we use Upstart to manage our uwsgi servers, something like this:

```
description "manage a uwsgi server"
start on (local-filesystems and runlevel [2345])
stop on runlevel [06]

chdir /SERVER/DIRECTORY

# this would handle restarting the server if it crashed
respawn
respawn limit 5 5

script
  exec uwsgi --ini /etc/uwsgi/SERVER_NAME.ini
end script
```

Which allows us to do things like:

    $ start SERVER_NAME
    $ restart SERVER_NAME
    $ stop SERVER_NAME

And a quick look at some of the [pm2 documentation](http://pm2.keymetrics.io/docs/usage/quick-start/) shows that pm2 should be able to do something similar:

    $ pm2 start endpoints -- --prefix=mycontroller --host=localhost:8000

That will start a basic endpoints server that would be managed by pm2.

I don't think we would add built-in support for something like this since there are so many mature libraries that already do it really well.

**Comment by Rafi993** [comment]
Thanks for the reply @Jaymon I decided to go with pm2 to be used with endpoint.
