### ISSUE TITLE
error in simple post request

### ISSUE THREAD

**Issue by Rafi993** [firstopinion/endpoints#55]
When I give simple post request I have the following error 

```
{
  "errno": 404,
  "errmsg": "/Foo not found because of TypeError \"not indexable\" on call.py:278"
}
```

my controller is as follows

```
class Foo(Controller,CorsMixin):
    def GET(self): pass
    def POST(self,**params):
        return "bang"

```

**Comment by Rafi993** [comment]
the above route works when I did curl for that route inside aws

**Comment by Jaymon** [comment]
What is the output from doing the POST in curl:

    $ curl -v http://HOST:LISTEN_IP/foo -d "bar=1"

And what do the server logs say?

I just copied your controller contents to a `controller.py` file and ran the command:

    $ endpoints-wsgiserver --prefix=controller --host localhost:8000

and then ran:

    $ curl http://localhost:8000/foo -d "bar=1"
    "bang"

Which is the correct response, so it seems to be working for me using version 1.1.17.

**Comment by Rafi993** [comment]
the curl works . while post from postman does not respond

**Comment by Jaymon** [comment]
My best guess is the box still isn't open to the outside world, either because of AWS security groups or Endpoints configuration, [this might help](https://github.com/firstopinion/endpoints/issues/54#issuecomment-245133083) to open the box up.

Some other things you can try, after you make a request on Postman, you can make sure it is received by endpoints by looking at the server logs, if endpoints doesn't receive anything then you know it is on the access side, and not the endpoint's side.

Good luck
